### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joao-paulo-parity**

### CODE REVIEW

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at "0x2d32f5d382ddb18ec8d5a89f0498e67df8d1de81f15d101850849cd82b143dd3" on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0x2d32f5d382ddb18ec8d5a89f0498e67df8d1de81f15d101850849cd82b143dd3 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0x2d32f5d382ddb18ec8d5a89f0498e67df8d1de81f15d101850849cd82b143dd3 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0x2d32f5d382ddb18ec8d5a89f0498e67df8d1de81f15d101850849cd82b143dd3 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0xff4a5c87bb3b725c8a0ee2e8581f5e2c618cf8555ec275f7af5759c46073e2b2 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0xff4a5c87bb3b725c8a0ee2e8581f5e2c618cf8555ec275f7af5759c46073e2b2 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0xff4a5c87bb3b725c8a0ee2e8581f5e2c618cf8555ec275f7af5759c46073e2b2 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0xff4a5c87bb3b725c8a0ee2e8581f5e2c618cf8555ec275f7af5759c46073e2b2 on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/try-runtime queue --url ws://westend --block-at 0x77c6752b0f5edd7bfd98112a75d52886a140240f1dd1c550af309a524183086e on-runtime-upgrade live

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by TarekkMA** [comment]
What is that??

**Pull request closed without merging**
